###############################################################################
# Basic site settings
###############################################################################
baseURL = 'https://blog.aothman.de'
languageCode = 'en-us'
defaultContentLanguage = "en"
title   = "Ahmed Othman | Search, Relevance & Leadership"

theme = 'DoIt'
#theme = 'ananke'
#theme = 'PaperMod'
