title = "Search, Relevance & Leadership"
description = "Deep dives into e-commerce search, ranking, vector retrieval and tech leadership."
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true
favicon = "/favicon.ico"

## — Blog Author    
[Author]
    name  = "Ahmed Othman"
    link  = "https://blog.aothman.de"
    email = "blog@aothman.de"
    avatar = "/images/aothman_avatar.jpg"         # optional – used in footer/SEO

## — header (logo / title if you want) —
[header]                    #  [oai_citation:1‡hugodoit.pages.dev](https://hugodoit.pages.dev/theme-documentation-basics/)
    logoLink = "/"                      # (optional) click-to-home
    [header.title]
        name = "Ahmed Othman | Search, Relevance & Leadership"
        logo = "/images/logo.png" # path to your logo; put the file in /static/images/            

## — home-page hero / profile —
[home]                      #  [oai_citation:2‡hugodoit.pages.dev](https://hugodoit.pages.dev/theme-documentation-basics/)
    # number of posts in RSS etc. (leave your values)
    rss = 10

    [home.profile]
        enable       = true            # turns the hero section on
        title        = "Search • Relevance • Tech Leadership"  # tagline line 1
        subtitle     = "Senior Technology Leader originally from Egypt 🇪🇬. Currently, looking after the Core Search teams at Zalando, based in Berlin, Germany 🇩🇪. Before that, I used to work as an Engineering Manager at Rakuten, based in Tokyo, Japan 🇯🇵."      # tagline line 2
        # Leave gravatarEmail empty if you set an avatar path above
        # gravatarEmail = "amedhat.cs@gmail.com"
        avatarURL = "/images/aothman_avatar.jpg"
        social = true            # show social icons under the avatar

###############################################################################
# Search Feature
###############################################################################

[search]                    #  [oai_citation:0‡hugodoit.pages.dev](https://hugodoit.pages.dev/theme-documentation-basics/)
    enable          = true           # shows the magnifying-glass icon
    type            = "fuse"         # simple, local, no API keys
    contentLength   = 4000           # how much of each post goes into the index
    maxResultLength = 10
    snippetLength   = 30
    highlightTag    = "em"
        
    [search.fuse]
        # DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
        isCaseSensitive = false
        minMatchCharLength = 2
        findAllMatches = false
        location = 0
        threshold = 0.3
        distance = 100
        ignoreLocation = false
        useExtendedSearch = false
        ignoreFieldNorm = false

###############################################################################
# Social icons used by the hero header & footer
###############################################################################

[social]
    GitHub   = "amedhat3"                     # username only → https://github.com/amedhat3
    Linkedin = "ahmed-othman"                 # username only → https://linkedin.com/in/ahmed-othman
    RSS      = true                           # show the RSS icon
    X  = "_ahmed_othman"                      # leave empty if you don’t use Twitter

# Table of the contents config
[page.toc]
    enable = true  # whether to enable the table of the contents
    keepStatic = false # whether to keep the static table of the contents in front of the post
    auto = true # whether to make the table of the contents in the sidebar automatically collapsed

###############################################################################
# Comments (giscus)
###############################################################################
[page.comment]
  enable = true                  # master switch for comments

    [page.comment.giscus] # giscus settings
        enable              = true   # must be true as well

        dataRepo            = "amedhat3/blog-aothman"       # required four IDs from giscus.app
        dataRepoId          = "MDEwOlJlcG9zaXRvcnkzMjQwMjA0OTg="
        dataCategory        = "blog-comments"
        dataCategoryId      = "DIC_kwDOE1ApEs4CtN-B"

        dataMapping         = "title"         # pathname / title / etc.
        dataReactionsEnabled = "1"
        dataEmitMetadata     = "0"
        dataInputPosition    = "bottom"
        dataLang             = "en"
        dataLoading          = "lazy"

        # let DoIt pick the right theme automatically
        lightTheme = "light"          # any giscus light theme
        darkTheme  = "dark"           # any giscus dark theme
