###############################################################################
# Basic site settings
###############################################################################
baseURL = 'https://blog.aothman.de'
languageCode = 'en-us'
defaultContentLanguage = "en"
title   = "Ahmed Othman | Search, Relevance & Leadership"

theme = 'DoIt'
#theme = 'ananke'
#theme = 'PaperMod'

###############################################################################
# Output formats – adds RSS and the JSON index (used by Lunr or Fuse.js)
###############################################################################
[outputs]
    home = ["HTML", "RSS", "JSON"]


[params]
    env = "production"
    title = "Search, Relevance & Leadership"
    description = "Deep dives into e-commerce search, ranking, vector retrieval and tech leadership."
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = false
    ShowCodeCopyButtons = true
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    UseHugoToc = true
    disableSpecial1stPost = false
    disableScrollToTop = false
    hidemeta = false
    hideSummary = false
    showtoc = true
    tocopen = true
    favicon = "/favicon.ico"
    
    [params.Author]
        name  = "Ahmed Othman"
        link  = "https://blog.aothman.de"
        email = "blog@aothman.de"
        avatar = "/images/aothman_avatar.jpg"         # optional – used in footer/SEO

    ## — header (logo / title if you want) —
    [params.header]                    #  [oai_citation:1‡hugodoit.pages.dev](https://hugodoit.pages.dev/theme-documentation-basics/)
        logoLink = "/"                      # (optional) click-to-home
        [params.header.title]
            name = "Ahmed Othman | Search, Relevance & Leadership"
            logo = "/images/logo.png" # path to your logo; put the file in /static/images/            

    ## — home-page hero / profile —
    [params.home]                      #  [oai_citation:2‡hugodoit.pages.dev](https://hugodoit.pages.dev/theme-documentation-basics/)
        # number of posts in RSS etc. (leave your values)
        rss = 10

        [params.home.profile]
            enable       = true            # turns the hero section on
            title        = "Search • Relevance • Tech Leadership"  # tagline line 1
            subtitle     = "Senior Technology Leader originally from Egypt 🇪🇬. Currently, looking after the Core Search teams at Zalando, based in Berlin, Germany 🇩🇪. Before that, I used to work as an Engineering Manager at Rakuten, based in Tokyo, Japan 🇯🇵."      # tagline line 2
            # Leave gravatarEmail empty if you set an avatar path above
            # gravatarEmail = "amedhat.cs@gmail.com"
            avatarURL = "/images/aothman_avatar.jpg"
            social = true            # show social icons under the avatar

###############################################################################
# Search Feature
###############################################################################

    [params.search]                    #  [oai_citation:0‡hugodoit.pages.dev](https://hugodoit.pages.dev/theme-documentation-basics/)
        enable          = true           # shows the magnifying-glass icon
        type            = "fuse"         # simple, local, no API keys
        contentLength   = 4000           # how much of each post goes into the index
        maxResultLength = 10
        snippetLength   = 30
        highlightTag    = "em"
            
            [params.search.fuse]
                # DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
                isCaseSensitive = false
                minMatchCharLength = 2
                findAllMatches = false
                location = 0
                threshold = 0.3
                distance = 100
                ignoreLocation = false
                useExtendedSearch = false
                ignoreFieldNorm = false

###############################################################################
# Social icons used by the hero header & footer
###############################################################################

[params.social]
GitHub   = "amedhat3"                     # username only → https://github.com/amedhat3
Linkedin = "ahmed-othman"                 # username only → https://linkedin.com/in/ahmed-othman
RSS      = true                           # show the RSS icon
X  = "_ahmed_othman"                             # leave empty if you don’t use Twitter
